name: Jay "Aevyz" L.
author: Aevyz
baseurl: ""
description: Project Hub
github: http://www.github.com/Aevyz
twitter: https://twitter.com/Aevyz_
##facebook: http://www.facebook.com
##linkedin: http://www.linkedin.com
email: j.aevyz [at] gmail [dot] com
location: Munich
disqus: aevyz

##Make sure to edit the above fields, especially for disqus.


highlighter: rouge ##pygments --> No Longer In Use
markdown: kramdown ##redcarpet -->No Longer in Use
##redcarpet: --> Not required
##  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
